use_frameworks!

platform :ios, '9.0'

target 'reuseableFramework_Example' do
  pod 'reuseableFramework', :path => '../'

  target 'reuseableFramework_Tests' do
    inherit! :search_paths

    
  end
end
